### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nameId' of null

### ISSUE THREAD

**Issue by Roustalski** [mulesoft/api-workbench#89]
[Enter steps to reproduce below:]

1. Created a NamedExample file with a header of "#%RAML 1.0 NamedExample"
2. Anytime I start typing content: into the edtior pane, I start getting all sorts of errors.
Alternatively, if I use the details pane and use the content text input, any character I try and type throws an "Uncaught TypeError: Cannot read property 'definition' of null", which is marked as closed under a different issue: https://github.com/mulesoft/api-workbench/issues/81

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.12

### Stack Trace

Uncaught TypeError: Cannot read property 'nameId' of null

```
At /Users/russwatson/.atom/packages/api-workbench/main.js:8

TypeError: Cannot read property 'nameId' of null
    at Object.y [as isExampleNodeContent] (/Users/russwatson/.atom/packages/api-workbench/main.js:8:18722)
    at h (/Users/russwatson/.atom/packages/api-workbench/main.js:30:10367)
    at y (/Users/russwatson/.atom/packages/api-workbench/main.js:30:14388)
    at Object.d [as getSuggestions] (/Users/russwatson/.atom/packages/api-workbench/main.js:30:12389)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -1:58.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:57 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:55.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:42.8.0 core:select-to-top (atom-text-editor.editor.is-focused)
     -1:42.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:41.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:24.1.0 core:select-up (atom-text-editor.editor.is-focused)
  4x -1:14.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:55.4.0 core:delete (atom-text-editor.editor.is-focused)
     -0:55 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:54 core:delete (atom-text-editor.editor.is-focused)
     -0:48.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:47.7.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -0:33.4.0 core:copy (div.raml-console.pane-item)
  3x -0:01.8.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.12
linter, v1.11.3

# Dev
No dev packages
```

**Comment by Roustalski** [comment]
Create a file with the following:

#%RAML 1.0 NamedExample
content: 'hmmmmm'

I am also referencing this from a resourceType using a relative path. Let me try including the file directly from a resource.

**Comment by ddenisenko** [comment]
Thank you, it is reproducible.

**Comment by ddenisenko** [comment]
Fixed. Fix is published in 0.8.15.

**Comment by daanoz** [comment]
I think this issue came back...

Using the same method as above the following exception is thrown: _TypeError: Cannot read property 'parsedType' of null_

Tested using api-workbench package, v0.8.28 in combination with atom stable 1.7.4 and atom beta 1.8.0-beta4

The stacktrace of the exception being thrown:

```
TypeError: Cannot read property 'parsedType' of null
    at Object.newVar.validate (C:\Users\<user>\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:2187:27)
    at ExampleValidator.validate (C:\Users\<user>\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:2046:20)
    at CompositePropertyValidator.validate (C:\Users\<user>\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:609:36)
    at Object.validate (C:\Users\<user>\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:379:42)
    at ASTPropImpl.BasicASTNode.validate (C:\Users\<user>\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:151:16)
    at C:\Users\<user>\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:346:15
    at Array.forEach (native)
    at validateBasic (C:\Users\<user>\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:342:12)
    at Object.validate (C:\Users\<user>\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:438:13)
    at ASTNodeImpl.BasicASTNode.validate (C:\Users\<user>\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:151:16)
    at u (C:\Users\<user>\.atom\packages\api-workbench\main.js:2:22116)
    at p (C:\Users\<user>\.atom\packages\api-workbench\main.js:2:21684)
    at Object.l [as lint] (C:\Users\<user>\.atom\packages\api-workbench\main.js:2:21132)
    at promises.push.Promise.then._this.emitter.emit.linter (C:/Users/<user>/.atom/packages/linter/lib/linter-registry.js:63:26)
    at C:/Users/<user>/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (C:/Users/<user>/.atom/packages/linter/lib/linter-registry.js:60:18)
    at file:///C:/Users/<user>/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:/Users/<user>/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\<user>\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\window-event-handler.js:3:61)
```

**Comment by simonkreuz** [comment]
Can this be re-opened? The issue came back for me too.

**Comment by ddenisenko** [comment]
@simonkreuz Could you please provide a complete reproduction sequence that results in exception? Also please post the exception itself.
